---

- name: Ensure that a SSH key has been especially created for Vagrant
  block:
    - ansible.builtin.command: ssh-keygen -t ed25519 -q -f ~/.ssh/vagrant -C "" -N ""
      args:
        creates: ~/.ssh/vagrant

  delegate_to: localhost
  become: false
  run_once: true

- name: Configure the vagrant account
  ansible.builtin.user:
    name: vagrant
    state: present
    shell: /bin/bash
    groups: sudo,ssh_authorized
    append: true
  when: not ansible_check_mode

- name: Add SSH key generated for Vagrant
  ansible.posix.authorized_key:
    user: vagrant
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/vagrant.pub') }}"
